ALTER TABLE tasks ADD COLUMN user_id INT;
DELETE FROM tasks;
ALTER TABLE tasks MODIFY COLUMN user_id INT NOT NULL;
ALTER TABLE tasks ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;


